title: Save File One â€” Archive
description: A playable museum of historically significant games and their lineage.
theme: jekyll-theme-minimal

baseurl: "/savefileone-archive"

collections:
  games:
    output: true
